### ISSUE TITLE
[EPIC] Creation Wizard (Build/Commerce)

### ISSUE THREAD

**Issue by philschanely** [Kajabi/sage-lib#1089]
## Description

The Build and Commerce teams are working on a Creation Flow modal experience that shares many aspects in common. Build will likely kick off the development and approach with Commerce following afterwards.

## Definition of Done

**Must have:** The design mockups from the linked files must be achievable with pixel-perfect precision. Generally speaking the follow efforts are involved.

- [ ] An overall full screen modal that allows for the two column layout and common header and footer components
- [ ] Audit of the smaller details in the left side (form) columns from each stage in the designed flows may lead to needs for new or modified components.
- [ ] The live-editing right side of features previews of the content being created and configured and will feature aspects that will update in real-time with edits from the left side. While the live wiring will be left to the product teams, we need to consider an approach to recommend as it pertains to what Sage does or does not provide.

See the linked Milestone for all related issues.

## Design

- [Product Creation Flow](https://www.figma.com/file/aYygNca9JqBoQs1VwwFyRd/Product-Creation-Flow?node-id=2740%3A15652)

![image](https://user-images.githubusercontent.com/17955295/145883227-94d483d7-f3b7-4f0e-a3ad-ddf42813c1fa.png)

- [Commerce Offer Creation Flow](https://www.figma.com/file/UfJlrF5IZTlKTstbKCaith/COMM-1494-Offer-Creation-Flow?node-id=1513%3A3092)

![image](https://user-images.githubusercontent.com/17955295/145883094-ace1644a-a62d-4450-b2b2-a9d4cb048fb6.png)

**Comment by philschanely** [comment]
Moved to Jira https://kajabi.atlassian.net/browse/UXD-39
