### ISSUE TITLE
[Epic] Create components for Contact Profile

### ISSUE THREAD

**Issue by monicawheeler** [Kajabi/sage-lib#880]
## Description

The Contact Profile slide-out feature planned for development by the Manage team contains new components and modifications to existing components.

## Definition of Done

**Must have:** The design mockup below must be achievable with pixel-perfect precision. These issues accomplish aspects of this goal:

- [x] #881 
  - [ ] Design: need to add to Figma spec file for SSoT
- [x] #885
  - [ ] Design: need to add to Figma spec file for SSoT
- [x] #882 
  - [x] Design: need to add to Figma spec file for SSoT
- [x] #884
  - [x] Design: need to export updated font icon set
- [x] #889 
- [x] #886 
- [x] #887
- [x] #888

**Nice to have:** Additional "sizzle" features for improved developer experience. The following issues are next-level polishes or nice-to-have features related to this effort:

- [ ] ~~#891~~ Moved out for general completion
- [x] #890

## Design
- [Figma Prototype](https://www.figma.com/proto/NQnIQAPgiLb6gQzNNGJidH/Contact-Profile?page-id=1197%3A19743&node-id=1830%3A41361&viewport=437%2C48%2C0.32&scaling=min-zoom&starting-point-node-id=1830%3A41361&show-proto-sidebar=1)
- [Figma panel detail](https://www.figma.com/file/NQnIQAPgiLb6gQzNNGJidH/Contact-Profile?node-id=1840%3A54240)
- [PoC Mockup](https://github.com/Kajabi/sage-lib/pull/878)

## Additional Information

Context:

![Screen Shot 2021-10-13 at 9 15 59 AM](https://user-images.githubusercontent.com/24237393/137151030-cc3f2858-0e3b-4952-a77c-1f43f403ef37.png)

Details (2x):

![image](https://user-images.githubusercontent.com/17955295/137303949-adfa62a3-005e-4afd-b798-a331087f61d1.png)
